### ISSUE TITLE
globalcanineregistry - need a GDPR inspection...

### ISSUE THREAD

**Issue by TallGuysFreeADMIN** [privacyradius/gdpr-tracker#105]
Having a GDPR form is one step, but so much more is required. I'm not really seeing that from globalcanineregistry. 
From terms of service: 
`GOVERNING LAW.
Any disputes arising out of or related to these Terms of Service and/or any use by you of the Site shall be governed by the laws of the **USA, without regard to the conflicts of laws provisions therein.**

DATE OF LAST UPDATE.
This agreement was last updated on November 8, **2012**.`

In the privacy, for cookies, they just mention you can turn them off. They do a great job explaining what cookies will be set and by what domain, but my understanding is cookies can't be forced.

**Comment by Gdewilde** [comment]
@adrianmejias can you take a look at the comments above? Can you provide some feedback about your compliance progress?

**Comment by adrianmejias** [comment]
@TallGuysFreeADMIN sure thing. i'm still in the process of updating frontend language as well as backend codebase. i will be looking into rewriting a portion of the terms of service page as the legal language is research intensive in regards to GDPR. i'm a one man crew so i do apologize for the slowness but that's no excuse.. everyone, including me, had more than enough time to get ready for GDPR.

from my understanding, a cookie consent must be present with clear language stating how they are used and an easy way to refuse said cookies (referenced in https://www.cookiebot.com/en/gdpr-cookies/). we leverage the use of onetrust.com cookie consent service for this item.

@Gdewilde i did set the status as 'In Progress', correct?

**Comment by Gdewilde** [comment]
@adrianmejias yes, you did.
