### ISSUE TITLE
CSS: overflow: scroll 

### ISSUE THREAD

**Issue by TallGuysFreeADMIN** [privacyradius/gdpr-tracker#98]
`overflow: scroll` should be changed to `overflow: auto` to remove the unusable horizontal scrollbar (bottom) on `.contentContainer`  (sidebar when viewing details))

**Comment by Gdewilde** [comment]
@Echelpoel can you pick this up on Monday?

**Comment by TallGuysFreeADMIN** [comment]
@Echelpoel just a friendly reminder :)
